# Generated by Django 2.1.7 on 2020-09-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0020_auto_20190731_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='exclude_words',
            field=models.TextField(default=''),
        ),
    ]
