# Generated by Django 2.1.7 on 2020-09-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0021_document_exclude_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_exclude_dictionary',
            field=models.TextField(default=''),
        ),
    ]
