# Generated by Django 2.1.7 on 2020-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0022_user_user_exclude_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='copy_of_user_user_exclude_dictionary',
            field=models.TextField(default=''),
        ),
    ]
